{
  "cpi": {
    "name": "cpi",
    "desc": "CPI",
    "summary": "socketcores",
    "url": "http://10.23.35.43:85/render?target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c0-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c1-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c2-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c3-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c4-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c5-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c6-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c7-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c16-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c17-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c18-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c19-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c20-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c21-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c22-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c23-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c24-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c8-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c9-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c10-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c11-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c12-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c13-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c14-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c15-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c25-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c26-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c27-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c28-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c29-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c30-cpi&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c31-cpi&from=-12h"
  },
  "csc-llc": {
    "name": "csc-llc",
    "desc": "Cache Contention",
    "summary": "socket",
    "url": "http://10.23.35.43:85/render?&from=-12h"
  },
  "gips": {
    "name": "gips",
    "desc": "GIPS",
    "summary": "socketcores",
    "url": "http://10.23.35.43:85/render?target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c0-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c1-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c2-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c3-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c4-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c5-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c6-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c7-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c16-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c17-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c18-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c19-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c20-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c21-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c22-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c23-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s0-cores-c24-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c8-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c9-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c10-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c11-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c12-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c13-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c14-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c15-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c25-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c26-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c27-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c28-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c29-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c30-gips&target=SAM.Node-Metrics.novamgmt21.sam-sockets-s1-cores-c31-gips&from=-12h"
  }
}